### ISSUE TITLE
npm registry url error

### ISSUE THREAD

**Issue by safiresh** [Bruce17/node-redis-rpc#1]
Hi, 

we unable to install this lib using "npm install node-redis-rpc" 
safireshs-MBP:TicketGoose safiresh$ npm install node-redis-rpc
npm ERR! fetch failed https://registry.npmjs.org/node-redis-rpc/-/node-redis-rpc-1.0.4.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by Bruce17** [comment]
Issue is fixed. Npm install should now work.
